/* fkwu-formeval.h — GENERATED from grammars/form-eval.fk (+ char_at/ord helpers).
   The form-eval meta-evaluator, embedded so `--feval` is self-contained (no runtime file dep).
   Regenerate: python3 scripts/gen_formeval_bundle.py  (do not hand-edit). */
static const char *fk_formeval_src =
  "(defn char_at (s i) (substring s i (add i 1)))\n(defn ord (c) (str_byte_at c 0))\n; form-eval.fk — the source tree-walk, in Form, on the BMF cursor: Form source string -> value, ev"
  "aluated AS it\n; is read, with NO flatten table. This dissolves the flatten knot: running a recipe no longer REQUIRES flattening —\n; the cursor reads and computes directly; flatte"
  "n becomes optional SPEED (the JIT path). Mirrors form-parse.fk's\n; recursive-descent over the cursor (no tokenizer, the BMF discipline), but each node returns its VALUE not a cell"
  ".\n;\n; Grammar form-eval now evaluates (a real meta-circular core + STRING/LIST/FLOAT values):\n;   expr   := integer | float | string | symbol | '(' form ')'\n;   float  := a num"
  "ber literal carrying '.' or 'e'/'E'  -> (str_to_float <literal-text>)\n;   string := '\"' ... '\"'  (escapes \\n \\\" \\\\ handled)   -> the literal's inner text\n;   form   := (op"
  " a b)            op in {add,sub,mul,div,mod,le,lt,gt,ge,eq}   ; binary builtins (float-aware)\n;           | (if c t e)                                                       ; cond"
  "itional\n;           | (let name val body)                                             ; lexical binding\n;           | (defn name (params...) body)                                "
  "    ; register a function\n;           | (do e1 e2 ...)                                                   ; sequence, threading env\n;           | (prim arg...)        prim a STRIN"
  "G/LIST kernel op               ; variadic, applied by name (fe-prim)\n;           | (fname arg...)        fname a user-defined function             ; THE meta-circular call\n;   sy"
  "mbol := lookup in the environment (a var bound by let, or an arg bound at a call)\n;\n; STRING/LIST/FLOAT values are OPAQUE to form-eval: a string/list/float value passes straight "
  "through the\n; (value end-pos env) triple; the kernel primitive (str_concat, head, str_to_float, ...) does the work. The new\n; work is mostly PARSING — fe-expr2 branches on '\"' ("
  "fe-str) and on a float-marker inside a number (fe-num); the\n; new ops route through fe-prim (collect args -> fe-prim-apply by name). String prims: str_concat str_eq substring\n; s"
  "tr_len str_byte_at str_to_float ; list prims: list cons head tail empty nth len.\n;\n; State threads as (value, end-pos, env). The ENV is the new thread: an assoc-list of bindings,"
  " each a cons-chain\n; cell terminated by integer 0 (our nil). Two entry kinds: variable (list name 0 value), and function\n; (list name 1 params body-pos) — params is a list of nam"
  "e-strings, body-pos the source position of the body expr,\n; re-evaluated under (current-env + arg bindings) on each call so a defn sees ITSELF (recursion is free).\n; This is the "
  "milestone: a recipe with a user-defined function — (do (defn f (n) (add n 1)) (f 5)) — runs THROUGH\n; the Form walker on the c-bootstrapped fkwu kernel, integers all the way down,"
  " no host interpreter.\n;\n; Four-way by grammars/tests/form-eval-band.fk (verdict 65535 — sixteen claims: 1..512 the meta-circular core,\n; 1024..32768 the STRING/LIST/FLOAT value "
  "kinds; the user-call milestone is claim 64).\n;\n; preludes: form-stdlib/core.fk\n\n(do\n    ; --- result triples (value end-pos env) ---\n    (defn fe-fst (pr) (head pr))\n    (de"
  "fn fe-snd (pr) (head (tail pr)))\n    (defn fe-thd (pr) (head (tail (tail pr))))\n    ; --- env: assoc-list, cons-chained, 0-terminated ---\n    (defn fe-emp () 0)\n    (defn fe-va"
  "r (nm vl) (list nm 0 vl))\n    (defn fe-fn (nm params bodypos) (list nm 1 params bodypos))\n    (defn fe-e-nm (e) (head e))\n    (defn fe-e-kind (e) (head (tail e)))\n    (defn fe-"
  "e-a (e) (head (tail (tail e))))\n    (defn fe-e-b (e) (head (tail (tail (tail e)))))\n    (defn fe-bind (env e) (cons e env))\n    (defn fe-look (env nm)\n        (if (eq env 0) 0"
  "\n            (if (str_eq (fe-e-nm (head env)) nm) (head env) (fe-look (tail env) nm))))\n    ; --- cursor primitives over the source string ---\n    (defn fe-at (s pos) (ord (char"
  "_at s pos)))\n    (defn fe-len (s) (str_len s))\n    (defn fe-isdigit (c) (and (ge c 48) (ge 57 c)))\n    (defn fe-isws (c) (if (eq c 32) 1 (if (eq c 10) 1 (if (eq c 13) 1 (if (eq "
  "c 9) 1 0)))))\n    (defn fe-isdelim (c) (if (eq (fe-isws c) 1) 1 (if (eq c 40) 1 (if (eq c 41) 1 0))))\n    (defn fe-skip (s pos)\n        (if (ge pos (fe-len s)) pos\n            "
  "(if (eq (fe-isws (fe-at s pos)) 1) (fe-skip s (add pos 1)) pos)))\n    (defn fe-digits (s pos acc)\n        (if (ge pos (fe-len s)) (list acc pos)\n            (if (fe-isdigit (fe-"
  "at s pos))\n                (fe-digits s (add pos 1) (add (mul acc 10) (sub (fe-at s pos) 48)))\n                (list acc pos))))\n    (defn fe-sym-end (s pos)\n        (if (ge po"
  "s (fe-len s)) pos\n            (if (eq (fe-isdelim (fe-at s pos)) 1) pos (fe-sym-end s (add pos 1)))))\n    ; advance past a closing ')' (with leading ws) — list terminator\n    (d"
  "efn fe-close (s pos)\n        (if (ge (fe-skip s pos) (fe-len s)) (fe-skip s pos) (add (fe-skip s pos) 1)))\n\n    ; --- expr := integer | float | string | symbol | '(' form ')' ; "
  "returns (value end-pos env) ---\n    ;   '\"' (char 34) opens a STRING literal; a number literal carrying '.' or 'e'/'E' is a FLOAT literal.\n    (defn fe-expr (s pos env) (fe-expr"
  "2 s (fe-skip s pos) env))\n    (defn fe-expr2 (s pos env)\n        (if (eq (fe-at s pos) 40) (fe-form s (add pos 1) env)\n            (if (eq (fe-at s pos) 34) (fe-str s pos env)\n"
  "                (if (fe-isdigit (fe-at s pos)) (fe-num s pos env) (fe-sym s pos env)))))\n    ; number literal: scan the whole token; if it carries '.' / 'e' / 'E' it is a FLOAT (s"
  "tr_to_float the\n    ; literal text), else an INTEGER (the existing digit-fold). Both return (value end-pos env).\n    (defn fe-num (s pos env)\n        (fe-num2 s pos (fe-sym-end "
  "s pos) env))\n    (defn fe-num2 (s a b env)\n        (if (eq (fe-isfloat s a b) 1)\n            (list (str_to_float (substring s a b)) b env)\n            (fe-int s a env)))\n    ;"
  " does the token s[a..b) contain a float marker ('.' 46 | 'e' 101 | 'E' 69) ?\n    (defn fe-isfloat (s a b)\n        (if (ge a b) 0\n            (if (eq (fe-at s a) 46) 1\n         "
  "       (if (eq (fe-at s a) 101) 1\n                    (if (eq (fe-at s a) 69) 1 (fe-isfloat s (add a 1) b))))))\n    (defn fe-int (s pos env)\n        (fe-int2 (fe-digits s pos 0)"
  " env))\n    (defn fe-int2 (d env) (list (fe-fst d) (fe-snd d) env))\n    ; --- string literal: from the opening '\"' at pos, scan to the closing '\"'; the VALUE is the\n    ;     l"
  "iteral's inner text (substring of the source). Escapes (\\\" \\\\ \\n) are handled minimally —\n    ;     see fe-str-end / fe-str-val. end-pos advances past the closing quote. ---"
  "\n    (defn fe-str (s pos env)\n        (fe-str2 s (add pos 1) (fe-str-end s (add pos 1)) env))\n    ; end of the literal's inner text: index of the closing '\"' (34), skipping esc"
  "aped chars.\n    (defn fe-str-end (s i)\n        (if (ge i (fe-len s)) i\n            (if (eq (fe-at s i) 34) i\n                (if (eq (fe-at s i) 92) (fe-str-end s (add i 2)) (f"
  "e-str-end s (add i 1))))))\n    ; value = unescaped inner text [a..b); end-pos = b+1 (past the closing quote)\n    (defn fe-str2 (s a b env) (list (fe-unesc s a b \"\") (add b 1) e"
  "nv))\n    ; build the unescaped string by walking [i..b): '\\' introduces an escape (\\n -> LF, \\\" -> \", \\\\ -> \\,\n    ; any other escaped char passes through literally). No-"
  "escape source returns its own substring.\n    (defn fe-unesc (s i b acc)\n        (if (ge i b) acc\n            (if (eq (fe-at s i) 92)\n                (fe-unesc s (add i 2) b (st"
  "r_concat acc (fe-esc-ch (fe-at s (add i 1)))))\n                (fe-unesc s (add i 1) b (str_concat acc (substring s i (add i 1)))))))\n    (defn fe-esc-ch (c)\n        (if (eq c 1"
  "10) \"\\n\"\n            (if (eq c 34) \"\\\"\"\n                (if (eq c 92) \"\\\\\" \"?\"))))\n    (defn fe-sym (s pos env)\n        (fe-sym2 s pos (fe-sym-end s pos) env))\n  "
  "  (defn fe-sym2 (s a b env)\n        (list (fe-e-a (fe-look env (substring s a b))) b env))\n\n    ; --- form := dispatch on the head symbol ---\n    (defn fe-form (s pos env) (fe-"
  "head s (fe-skip s pos) env))\n    (defn fe-head (s pos env) (fe-disp (substring s pos (fe-sym-end s pos)) s (fe-sym-end s pos) env))\n    (defn fe-disp (op s pos env)\n        (if "
  "(str_eq op \"if\") (fe-if s pos env)\n            (if (str_eq op \"let\") (fe-let s pos env)\n                (if (str_eq op \"do\") (fe-do s pos env)\n                    (if (str"
  "_eq op \"defn\") (fe-defn s pos env)\n                        (if (fe-isbuiltin op) (fe-bin op s pos env)\n                            (if (fe-isprim op) (fe-prim op s pos env)\n  "
  "                              (fe-call op s pos env))))))))\n    (defn fe-isbuiltin (op)\n        (if (str_eq op \"add\") 1 (if (str_eq op \"sub\") 1 (if (str_eq op \"mul\") 1\n   "
  "         (if (str_eq op \"div\") 1 (if (str_eq op \"mod\") 1 (if (str_eq op \"le\") 1\n                (if (str_eq op \"lt\") 1 (if (str_eq op \"gt\") 1 (if (str_eq op \"ge\") 1\n "
  "                   (if (str_eq op \"eq\") 1 0)))))))))))\n    ; primitive (string/list/float) kernel ops — variadic-arity, collected then applied by name.\n    (defn fe-isprim (op)"
  "\n        (if (str_eq op \"str_concat\") 1\n        (if (str_eq op \"str_eq\") 1\n        (if (str_eq op \"substring\") 1\n        (if (str_eq op \"str_len\") 1\n        (if (str_e"
  "q op \"str_byte_at\") 1\n        (if (str_eq op \"str_to_float\") 1\n        (if (str_eq op \"list\") 1\n        (if (str_eq op \"cons\") 1\n        (if (str_eq op \"head\") 1\n   "
  "     (if (str_eq op \"tail\") 1\n        (if (str_eq op \"empty\") 1\n        (if (str_eq op \"nth\") 1\n        (if (str_eq op \"len\") 1 0))))))))))))))\n\n    ; --- binary built"
  "in: (op a b) ---\n    (defn fe-bin (op s pos env) (fe-bin-a op s (fe-expr s pos env)))\n    (defn fe-bin-a (op s ae) (fe-bin-b op s (fe-fst ae) (fe-expr s (fe-snd ae) (fe-thd ae)))"
  ")\n    (defn fe-bin-b (op s a be)\n        (list (fe-apply op a (fe-fst be)) (fe-close s (fe-snd be)) (fe-thd be)))\n    (defn fe-apply (op a b)\n        (if (str_eq op \"add\") (a"
  "dd a b)\n        (if (str_eq op \"sub\") (sub a b)\n        (if (str_eq op \"mul\") (mul a b)\n        (if (str_eq op \"div\") (div a b)\n        (if (str_eq op \"mod\") (mod a b)"
  "\n        (if (str_eq op \"le\") (if (le a b) 1 0)\n        (if (str_eq op \"lt\") (if (lt a b) 1 0)\n        (if (str_eq op \"gt\") (if (gt a b) 1 0)\n        (if (str_eq op \"ge"
  "\") (if (ge a b) 1 0)\n        (if (str_eq op \"eq\") (if (eq a b) 1 0) 0)))))))))))\n\n    ; --- primitive (string / list / float) ops: (op arg...) — variadic-arity.\n    ;     Co"
  "llect ALL args into a value-list (the same cons-chain fe-args builds for user calls), then\n    ;     apply the kernel op by name, pulling positional args by head/tail. The values "
  "are OPAQUE to\n    ;     form-eval — a string value, list value, or float value passes straight through (value end-pos env). ---\n    (defn fe-prim (op s pos env) (fe-prim-fin op s"
  " (fe-args s pos env)))\n    (defn fe-prim-fin (op s av)\n        (list (fe-prim-apply op (fe-fst av)) (fe-snd av) (fe-thd av)))\n    ; positional arg accessors over the collected v"
  "alue-list\n    (defn fe-a0 (vs) (head vs))\n    (defn fe-a1 (vs) (head (tail vs)))\n    (defn fe-a2 (vs) (head (tail (tail vs))))\n    (defn fe-prim-apply (op vs)\n        (if (str"
  "_eq op \"list\") vs\n        (if (str_eq op \"empty\") (empty)\n        (if (str_eq op \"str_concat\") (str_concat (fe-a0 vs) (fe-a1 vs))\n        (if (str_eq op \"str_eq\") (if (s"
  "tr_eq (fe-a0 vs) (fe-a1 vs)) 1 0)\n        (if (str_eq op \"substring\") (substring (fe-a0 vs) (fe-a1 vs) (fe-a2 vs))\n        (if (str_eq op \"str_len\") (str_len (fe-a0 vs))\n   "
  "     (if (str_eq op \"str_byte_at\") (str_byte_at (fe-a0 vs) (fe-a1 vs))\n        (if (str_eq op \"str_to_float\") (str_to_float (fe-a0 vs))\n        (if (str_eq op \"cons\") (cons"
  " (fe-a0 vs) (fe-a1 vs))\n        (if (str_eq op \"head\") (head (fe-a0 vs))\n        (if (str_eq op \"tail\") (tail (fe-a0 vs))\n        (if (str_eq op \"nth\") (nth (fe-a0 vs) (fe"
  "-a1 vs))\n        (if (str_eq op \"len\") (len (fe-a0 vs)) 0))))))))))))))\n\n    ; --- conditional: (if c t e) — evaluate c, then only the taken branch must be evaluated for value"
  ",\n    ;     but we evaluate both arms for position to find the close (pure walk, no host short-circuit needed\n    ;     for correctness here since arms are pure). We thread the c"
  "ond's env into both arms. ---\n    ; SHORT-CIRCUIT is load-bearing: only the taken arm is evaluated, the other is merely SKIPPED for position.\n    ; (Without this a recursive (if "
  "base 0 (recur)) never terminates — the dead arm would recurse forever.)\n    (defn fe-if (s pos env) (fe-if-c s (fe-expr s pos env)))\n    (defn fe-if-c (s ce) (fe-if-arms s (fe-fs"
  "t ce) (fe-snd ce) (fe-thd ce)))\n    (defn fe-if-arms (s c tpos env)\n        (if (eq c 0)\n            (fe-if-pick s env (fe-skip-expr s tpos))           ; cond false: then-end is"
  " else-start\n            (fe-if-then s env (fe-expr s tpos env))))           ; cond true: eval then, then skip else\n    ; cond true: te = (val then-end env'); skip the else arm; c"
  "lose past the if's ')'\n    (defn fe-if-then (s env te)\n        (list (fe-fst te) (fe-close s (fe-skip-expr s (fe-snd te))) (fe-thd te)))\n    ; cond false: evaluate the else arm "
  "(which begins at epos), close past the if's ')'\n    (defn fe-if-pick (s env epos) (fe-if-else s (fe-expr s epos env)))\n    (defn fe-if-else (s ee) (list (fe-fst ee) (fe-close s ("
  "fe-snd ee)) (fe-thd ee)))\n\n    ; --- let: (let name val body) — bind name to val, eval body in the extended env,\n    ;     return body's value; the binding does NOT escape (env "
  "returned is the original). ---\n    (defn fe-let (s pos env)\n        (fe-let-nm s (fe-skip s pos) env))\n    (defn fe-let-nm (s pos env)\n        (fe-let-v s (fe-sym-end s pos) (s"
  "ubstring s pos (fe-sym-end s pos)) env))\n    (defn fe-let-v (s pos nm env)\n        (fe-let-b s nm env (fe-expr s pos env)))\n    (defn fe-let-b (s nm env ve)\n        (fe-let-fin"
  " s env (fe-expr s (fe-snd ve)\n            (fe-bind env (fe-var nm (fe-fst ve))))))\n    ; after the body we sit at the body's end; advance past the let's own ')'; binding does NOT"
  " escape (env0).\n    (defn fe-let-fin (s env0 be)\n        (list (fe-fst be) (fe-close s (fe-snd be)) env0))\n\n    ; --- do: (e1 e2 ... ) — evaluate each child threading env child"
  "-to-child, value is the last child's. ---\n    (defn fe-do (s pos env) (fe-do-loop s (fe-skip s pos) env 0))\n    (defn fe-do-loop (s pos env last)\n        (if (eq (fe-at s pos) 4"
  "1) (list last (add pos 1) env)\n            (fe-do-step s (fe-expr s pos env))))\n    (defn fe-do-step (s ce)\n        (fe-do-loop s (fe-skip s (fe-snd ce)) (fe-thd ce) (fe-fst ce)"
  "))\n\n    ; --- defn: (defn name (params...) body) — register a function entry, skip the body, extend env. ---\n    (defn fe-defn (s pos env) (fe-defn-nm s (fe-skip s pos) env))\n "
  "   (defn fe-defn-nm (s pos env)\n        (fe-defn-p s (fe-sym-end s pos) (substring s pos (fe-sym-end s pos)) env))\n    ; params list begins at '(' ; collect param name-strings\n "
  "   (defn fe-defn-p (s pos nm env)\n        (fe-defn-b s nm (fe-params s (add (fe-skip s pos) 1)) env))\n    ; body begins right after the params ')' ; we DON'T evaluate it now — st"
  "ore its position\n    (defn fe-defn-b (s nm pe env)\n        (fe-defn-fin s nm (fe-fst pe) (fe-skip s (fe-snd pe)) env))\n    (defn fe-defn-fin (s nm params bodypos env)\n        ("
  "list 0 (fe-close s (fe-skip-expr s bodypos))\n            (fe-bind env (fe-fn nm params bodypos))))\n    ; collect param names until ')' ; returns (params-list end-pos)\n    (defn "
  "fe-params (s pos)\n        (if (eq (fe-at s (fe-skip s pos)) 41) (list 0 (add (fe-skip s pos) 1))\n            (fe-params-step s (fe-skip s pos))))\n    (defn fe-params-step (s pos"
  ")\n        (fe-params-cons (substring s pos (fe-sym-end s pos)) (fe-params s (fe-sym-end s pos))))\n    (defn fe-params-cons (nm rest) (list (cons nm (fe-fst rest)) (fe-snd rest)))"
  "\n\n    ; --- skip an expression (no eval) — needed to find a defn body's end without evaluating it.\n    ;     Returns the end-pos just past the expression. ---\n    (defn fe-skip"
  "-expr (s pos) (fe-skip-expr2 s (fe-skip s pos)))\n    ; a string literal is skipped to just past its closing '\"'; a number (int OR float) ends at the next\n    ; delimiter (fe-sym"
  "-end carries '.' 'e' 'E'); a symbol likewise. '\"' must be checked before the\n    ; number/symbol cases since fe-sym-end would stop at whitespace INSIDE a quoted string.\n    (def"
  "n fe-skip-expr2 (s pos)\n        (if (eq (fe-at s pos) 40) (fe-skip-list s (add pos 1))\n            (if (eq (fe-at s pos) 34) (add (fe-str-end s (add pos 1)) 1)\n                ("
  "fe-sym-end s pos))))\n    (defn fe-skip-list (s pos)\n        (if (eq (fe-at s (fe-skip s pos)) 41) (add (fe-skip s pos) 1)\n            (fe-skip-list s (fe-skip-expr s (fe-skip s "
  "pos)))))\n\n    ; --- user call: (fname arg...) — look up fn, evaluate args, bind to params, eval body. ---\n    (defn fe-call (op s pos env)\n        (fe-call-f op env (fe-look en"
  "v op) s pos env))\n    (defn fe-call-f (op env fn s pos callenv)\n        (fe-call-a fn s (fe-args s pos callenv) callenv))\n    ; fe-args collects (arg-values-list end-pos env) — "
  "env threads through arg eval\n    (defn fe-args (s pos env)\n        (if (eq (fe-at s (fe-skip s pos)) 41) (list 0 (add (fe-skip s pos) 1) env)\n            (fe-args-step s (fe-exp"
  "r s pos env))))\n    (defn fe-args-step (s ae) (fe-args-cons (fe-fst ae) (fe-args s (fe-snd ae) (fe-thd ae))))\n    (defn fe-args-cons (v rest) (list (cons v (fe-fst rest)) (fe-snd"
  " rest) (fe-thd rest)))\n    ; bind params to arg values atop the call env, then eval the body at the stored position\n    (defn fe-call-a (fn s av callenv)\n        (fe-call-b fn s"
  " (fe-fst av) (fe-snd av) callenv))\n    (defn fe-call-b (fn s args endpos callenv)\n        (list (fe-fst (fe-expr s (fe-e-b fn)\n                  (fe-zip (fe-e-a fn) args callenv"
  ")))\n              endpos callenv))\n    ; zip params (name-list) with args (value-list) into env entries\n    (defn fe-zip (params args env)\n        (if (eq params 0) env\n      "
  "      (fe-zip (tail params) (tail args)\n                (fe-bind env (fe-var (head params) (head args))))))\n\n    ; --- entry point ---\n    (defn fe-eval (s) (fe-fst (fe-expr s "
  "0 (fe-emp)))))\n"
;
