/* Generated by Form: observe/native-node-word-generate.bml. */
#ifndef FK_NODE_WORD_H
#define FK_NODE_WORD_H
typedef unsigned long long fk_node_id;
_Static_assert(sizeof(fk_node_id) == 8, "node identity requires a 64-bit word");
#define FK_NID_PACKAGE_BITS 6
#define FK_NID_LEVEL_BITS 13
#define FK_NID_TYPE_BITS 12
#define FK_NID_INSTANCE_BITS 32
#define FK_NID_LEVEL_SHIFT (FK_NID_INSTANCE_BITS + FK_NID_TYPE_BITS)
#define FK_NID_PACKAGE_SHIFT (FK_NID_LEVEL_SHIFT + FK_NID_LEVEL_BITS)
#define FK_NID_MASK(bits) ((1ULL << (bits)) - 1ULL)
#define FK_NID_MODE (1ULL << 63)
_Static_assert(1 + FK_NID_PACKAGE_BITS + FK_NID_LEVEL_BITS + FK_NID_TYPE_BITS + FK_NID_INSTANCE_BITS == 64, "node identity fields must occupy one word");
static int fk_nid_fits(long long p, long long l, long long t, long long i) {
    if (p == 1 && l == 1 && t == 1) { return i >= -(1LL << 62) && i < (1LL << 62); }
    return p >= 0 && (fk_node_id)p <= FK_NID_MASK(FK_NID_PACKAGE_BITS) &&
           l >= 0 && (fk_node_id)l <= FK_NID_MASK(FK_NID_LEVEL_BITS) &&
           t >= 0 && (fk_node_id)t <= FK_NID_MASK(FK_NID_TYPE_BITS) &&
           i >= 0 && (fk_node_id)i <= FK_NID_MASK(FK_NID_INSTANCE_BITS);
}
static fk_node_id fk_nid_make(long long p, long long l, long long t, long long i) {
    if (!fk_nid_fits(p, l, t, i)) { fk_die("fkwu: coordinate is outside the native 64-bit node identity layout"); }
    if (p == 1 && l == 1 && t == 1) { return ((fk_node_id)i) & ~FK_NID_MODE; }
    return FK_NID_MODE | ((fk_node_id)p << FK_NID_PACKAGE_SHIFT) | ((fk_node_id)l << FK_NID_LEVEL_SHIFT) | ((fk_node_id)t << FK_NID_INSTANCE_BITS) | (fk_node_id)i;
}
static long long fk_nid_get(fk_node_id id, int field) {
    if (!(id & FK_NID_MODE)) {
        if (field != 3) { return 1; }
        return id & (1ULL << 62) ? -1 - (long long)((~id) & ~FK_NID_MODE) : (long long)id;
    }
    if (field == 0) { return (long long)((id >> FK_NID_PACKAGE_SHIFT) & FK_NID_MASK(FK_NID_PACKAGE_BITS)); }
    if (field == 1) { return (long long)((id >> FK_NID_LEVEL_SHIFT) & FK_NID_MASK(FK_NID_LEVEL_BITS)); }
    if (field == 2) { return (long long)((id >> FK_NID_INSTANCE_BITS) & FK_NID_MASK(FK_NID_TYPE_BITS)); }
    return (long long)(id & FK_NID_MASK(FK_NID_INSTANCE_BITS));
}
#endif
