#!/usr/bin/env python3
"""gen-body-index.py — regenerate plugin/body-index.fk: a lexical index over the
body's knowledge cells, so the door's /ask retrieves over the WHOLE body (~1500
cells) instead of a 13-entry hand-curated seed.

Build tooling, NOT runtime: this emits a Form DATA file the fkwu door loads. The
index is a regenerable cache (like T_flat) — rerun after cells change. Run from
the repo root:  python3 plugin/gen-body-index.py

Each entry is (cp-entry id path summary keys); a companion prebaked nodeid table
carries each cell's sha256 (IDENTICAL to the body's own sha256.fk recipe output —
verified byte-for-byte against `shasum -a 256` — so the served NodeID is the same
content address the recipe would compute, just hashed once at build time, not at
boot). Concatenated AFTER chatgpt-plugin.fk, its cp-index and cp-nid-table
override the curated fallbacks (later defn wins on fkwu, verified).
"""
import os, re, glob, hashlib
from collections import Counter

STOP = set("i me my mine you your yours we us our ours it its they them their this that these those a an the is am are was were be been being do does did can could will would shall should may might must have has had and or but of to in on at for with from by as if so what how why when where who whom which whose not no yes here there".split())

CORPUS_GLOBS = [
    'form/form-stdlib/*.fk', 'receipts/*.md', 'docs/**/*.md',
    'axioms/*.form', 'axioms/*.fk', 'surface/*.fk', 'learn/*.fk',
    'observe/*.fk', 'ingest/*.fk', 'cognition/*.fk', '*.md',
]
KEYS_CAP = 40
TOK = re.compile(r'[a-z0-9]+')

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ').replace('\r', ' ').replace('\t', ' ')

def header(path, txt):
    for line in txt.splitlines():
        s = line.strip()
        if path.endswith('.md'):
            if s and not s.startswith('!['):
                return s.lstrip('#').strip()[:180]
        else:  # .fk / .form: first comment line
            if s.startswith(';'):
                body = s.lstrip(';').strip()
                if body:
                    return body[:180]
    return os.path.basename(path)

def main():
    paths = []
    for g in CORPUS_GLOBS:
        paths += glob.glob(g, recursive=True)
    paths = sorted(set(p for p in paths if os.path.isfile(p)))
    entries, nids = [], []
    for p in paths:
        raw = open(p, 'rb').read()
        txt = raw.decode('utf-8', 'ignore')
        low = txt.lower()
        toks = [t for t in TOK.findall(low) if len(t) > 2 and t not in STOP]
        if not toks:
            continue
        keys = [w for w, _ in Counter(toks).most_common(KEYS_CAP)]
        nodeid = 'sha256:' + hashlib.sha256(raw).hexdigest()
        summ = esc(header(p, txt))
        keys_fk = ' '.join(f'"{esc(k)}"' for k in keys)
        entries.append(f'        (cp-entry "{esc(p)}" "{esc(p)}" "{summ}" (list {keys_fk}))')
        nids.append(f'        (list "{esc(p)}" "{nodeid}")')
    out = []
    out.append('; body-index.fk — GENERATED by plugin/gen-body-index.py. Do not edit by hand.')
    out.append('; A lexical index over the body\'s knowledge cells so /ask retrieves over the')
    out.append(f'; whole body ({len(entries)} cells), not a 13-entry seed. Overrides cp-index and')
    out.append('; cp-nid-table (later defn wins). NodeIDs are prebaked sha256 == the body\'s own')
    out.append('; sha256.fk recipe output (verified). Regenerable cache; rerun the generator when')
    out.append('; cells change. preludes: form-stdlib/core.fk plugin/chatgpt-plugin.fk')
    out.append('(do')
    out.append('    (defn cp-index () (list')
    out.append('\n'.join(entries))
    out.append('        ))')
    out.append('    (defn cp-nid-table () (list')
    out.append('\n'.join(nids))
    out.append('        ))')
    out.append('    0)')
    open('plugin/body-index.fk', 'w').write('\n'.join(out) + '\n')
    print(f'wrote plugin/body-index.fk: {len(entries)} cells, {os.path.getsize("plugin/body-index.fk")/1024/1024:.2f} MB')

if __name__ == '__main__':
    main()
