#!/usr/bin/env bash
# Build the compact 10k × 13 OMW semantic surface without Python.
# Usage: cognition/concept-nl-semantic-13-build.sh /path/to/omw-data
set -euo pipefail

source_repo=${1:?usage: concept-nl-semantic-13-build.sh /path/to/omw-data}
pinned_commit=406bf83b3c507a3d1f26e88252d5d66893fd36bf
actual_commit=$(git -C "$source_repo" rev-parse HEAD)
if [[ "$actual_commit" != "$pinned_commit" ]]; then
  echo "OMW commit mismatch: expected $pinned_commit, got $actual_commit" >&2
  exit 1
fi

repo_root=$(git rev-parse --show-toplevel)
output_base="$repo_root/cognition/concept-nl-semantic-13"
build_tmp=$(mktemp -d /tmp/concept-nl-semantic-13.XXXXXX)
trap 'rm -rf "$build_tmp"' EXIT

codes=(eng ind spa fra por swa deu rus cmn jpn arb hin tur)
lenses=(en id es fr pt-br sw de ru zh ja ar hi tr)

LC_ALL=C awk -F $'\t' '
  $2 == "eng:lemma" && $3 != "" && !seen[$1]++ { print $1; count++ }
  count == 10000 { exit }
' "$source_repo/wns/wikt/wn-wikt-eng.tab" > "$build_tmp/anchors"

if [[ $(wc -l < "$build_tmp/anchors" | tr -d ' ') != 10000 ]]; then
  echo "anchor extraction did not produce exactly 10000 synsets" >&2
  exit 1
fi

for code in "${codes[@]}"; do
  LC_ALL=C awk -F $'\t' -v wanted_code="$code" '
    NR == FNR { wanted[$1] = 1; next }
    $2 == wanted_code ":lemma" && $3 != "" && wanted[$1] && !seen[$1]++ {
      label=$3
      gsub(/\r/, "", label)
      print $1 "\t" label
    }
  ' "$build_tmp/anchors" "$source_repo/wns/wikt/wn-wikt-$code.tab" \
    > "$build_tmp/$code"
done

LC_ALL=C awk -F $'\t' \
  -v codes="${codes[*]}" -v lenses="${lenses[*]}" '
  NR == FNR { anchors[++anchor_count]=$1; next }
  {
    file=FILENAME
    sub(/^.*\//, "", file)
    labels[file SUBSEP $1]=$2
  }
  END {
    code_count=split(codes, code_order, " ")
    lens_count=split(lenses, lens_order, " ")
    printf "synset"
    for (j=1; j<=lens_count; j++) printf "\t%s", lens_order[j]
    printf "\n"
    for (i=1; i<=anchor_count; i++) {
      anchor=anchors[i]
      printf "%s", anchor
      for (j=1; j<=code_count; j++) printf "\t%s", labels[code_order[j] SUBSEP anchor]
      printf "\n"
    }
  }
' "$build_tmp/anchors" \
  "$build_tmp/eng" "$build_tmp/ind" "$build_tmp/spa" "$build_tmp/fra" \
  "$build_tmp/por" "$build_tmp/swa" "$build_tmp/deu" "$build_tmp/rus" \
  "$build_tmp/cmn" "$build_tmp/jpn" "$build_tmp/arb" "$build_tmp/hin" \
  "$build_tmp/tur" > "$output_base-omw.tsv"

{
  echo '; concept-nl-semantic-13-offsets.fk — generated byte offsets for 10k OMW rows.'
  echo '; witnessed: 2026-07-18 -> 8191 live fkwu'
  echo '; preludes: form/form-stdlib/core.fk'
  echo '(do'
  echo '  (defn cnl13-offsets () (list'
  LC_ALL=C awk 'NR == 1 { offset=length($0)+1; next }
    { print "    " offset; offset += length($0)+1 }
    END { print "    " offset }
  ' "$output_base-omw.tsv"
  echo '  ))'
  echo ')'
} > "$output_base-offsets.fk"

cp "$source_repo/wns/wikt/LICENSE" "$output_base-omw-license.txt"

selected_hash=$(shasum -a 256 "$output_base-omw.tsv" | awk '{print $1}')
{
  echo '; concept-nl-semantic-13-metadata.fk — generated OMW provenance and exact coverage.'
  echo '; witnessed: 2026-07-18 -> 255 four-way; 8191 live fkwu'
  echo '; preludes: form/form-stdlib/core.fk'
  echo '(do'
  echo '  (defn cnl13-source-meta ()'
  echo '    (list "https://github.com/omwn/omw-data"'
  echo "          \"$pinned_commit\""
  echo '          "CC-BY-SA-3.0-and-GFDL-1.1-or-later"'
  echo "          \"$selected_hash\""
  echo '          10000'
  echo '          "first-10000-unique-eng-synsets"'
  echo '          "first-non-empty-wiktionary-lemma"'
  echo '          "automatic-mapped-unreviewed"))'
  echo '  (defn cnl13-locale-meta-rows () (list'
  for locale_index in "${!codes[@]}"; do
    code=${codes[$locale_index]}
    lens=${lenses[$locale_index]}
    column=$((locale_index + 2))
    present=$(LC_ALL=C awk -F $'\t' -v col="$column" 'NR > 1 && $col != "" { n++ } END { print n+0 }' "$output_base-omw.tsv")
    absent=$((10000 - present))
    source_hash=$(shasum -a 256 "$source_repo/wns/wikt/wn-wikt-$code.tab" | awk '{print $1}')
    echo "    (list \"$lens\" \"$code\" $present $absent \"$source_hash\" \"mapped-unreviewed\")"
  done
  echo '  ))'
  echo ')'
} > "$output_base-metadata.fk"

{
  echo "source=https://github.com/omwn/omw-data"
  echo "commit=$pinned_commit"
  echo "selection=first-10000-unique-eng-lemma-synsets-in-source-order"
  echo "label=first-non-empty-lemma-per-selected-synset-in-each-source-file"
  echo "license=CC-BY-SA-3.0-and-GFDL-1.1-or-later"
  for code in "${codes[@]}"; do
    source_hash=$(shasum -a 256 "$source_repo/wns/wikt/wn-wikt-$code.tab" | awk '{print $1}')
    echo "$source_hash  wn-wikt-$code.tab"
  done
  echo "$selected_hash  concept-nl-semantic-13-omw.tsv"
} > "$output_base-source-manifest.txt"

echo "built $output_base-omw.tsv"
wc -l "$output_base-omw.tsv"
