// jit_value.go — Value-typed JIT: compile ANY recipe to a native Go plugin.
//
// The int64 JIT (jit.go) lowers an integer-only subset and refuses lists,
// strings, and native calls. This path removes those walls by compiling to
// the kernel's full runtime value — core.Value — and by emitting native and
// cross-function calls as a `dispatch` callback the kernel supplies. The
// recipe stays canonical truth; this is just a faster way to evaluate it.
//
// Shape of the generated plugin:
//
//   func Fn(args []core.Value, dispatch func(uint32, []core.Value) core.Value) core.Value {
//       var self func([]core.Value) core.Value
//       self = func(a []core.Value) core.Value {
//           // per-call frame: every param + let name is a Go var here, so
//           // a `let` mutates the frame and leaks to later siblings exactly
//           // as Form's flat call-frame does; if/and/or IIFEs capture them.
//           var v_<p0> core.Value = a[0]
//           var v_<letx> core.Value
//           return <body>          // self(...) recursion, dispatch(id,...) calls
//       }
//       return self(args)
//   }
//
// Native calls and calls to OTHER Form functions both emit dispatch(nameID,
// args); the kernel's dispatch closure (callValueByName) resolves the name to
// an env-aware native, a plain native, or another closure — walking it or
// running its own JIT'd plugin. Self-recursion stays a direct self() call.
//
// The plugin imports form-kernel-go/core (the shared value package) and so is
// built against the kernel's own module via a replace directive pointing at
// the kernel source root (FORM_KERNEL_SRC, or detected from cwd / argv0).
// When the source root isn't available (a deployed binary without its source),
// the compile returns an error and the walker keeps running — same answer.

package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"plugin"
	"strconv"
	"strings"

	"form-kernel-go/core"
)

// jitValueFn — the signature every Value-typed plugin's Fn symbol carries.
// args are the call arguments; dispatch resolves a callee NameID (native or
// closure) to its result. Defined as an alias so plugin.Lookup's type assert
// matches the symbol the plugin exports byte-for-byte.
type jitValueFn = func(args []core.Value, dispatch func(uint32, []core.Value) core.Value) core.Value

// vScope — name resolution during Value-typed emission. frame maps a NameID
// (param or let) to its Go var name; selfName/selfFn route recursion.
type vScope struct {
	frame    map[NameID]string
	selfName NameID
}

func vVar(id NameID) string { return fmt.Sprintf("v_%d", uint32(id)) }

// collectFrameVars — walk the body collecting every NameID introduced by a
// LET, so they can be declared once at frame scope (Form's let is
// frame-scoped, not block-scoped: it mutates the single call frame).
func collectFrameVars(k *Kernel, node NodeID, out map[NameID]bool) {
	if node.Level == LevelTrivial {
		return
	}
	cat := k.category(node)
	kids := k.children(node)
	if cat.Type == RBasicBlock && cat.Inst == RBlockLet && len(kids) >= 1 {
		out[k.identID(kids[0])] = true
	}
	for _, c := range kids {
		collectFrameVars(k, c, out)
	}
}

// jitCompileClosureValueGo — compile a closure to a Value-typed native plugin.
func jitCompileClosureValueGo(k *Kernel, cl *Closure) (jitValueFn, error) {
	srcRoot, err := kernelSourceRoot()
	if err != nil {
		return nil, err
	}

	scope := &vScope{frame: map[NameID]string{}, selfName: cl.Name}
	// params occupy the frame first (initialised from args), then lets.
	for _, p := range cl.Params {
		scope.frame[p] = vVar(p)
	}
	letNames := map[NameID]bool{}
	collectFrameVars(k, cl.Body, letNames)
	for id := range letNames {
		if _, isParam := scope.frame[id]; !isParam {
			scope.frame[id] = vVar(id)
		}
	}

	bodySrc, err := emitVExpr(k, cl.Body, scope)
	if err != nil {
		return nil, err
	}

	var src strings.Builder
	src.WriteString("// Generated by form-kernel-go JIT (Value-typed) — Form recipe → Go.\n")
	src.WriteString("// Closure: " + k.nameStr(cl.Name) + "  body NodeID: " + nodeIDKey(cl.Body) + "\n")
	src.WriteString("// Throwaway expression of a canonical recipe; runs native via plugin.Open.\n\n")
	src.WriteString("package main\n\n")
	src.WriteString("import (\n\t\"math\"\n\n\t\"form-kernel-go/core\"\n)\n\n")
	src.WriteString("var _ = math.Floor\n\n")
	src.WriteString(vRuntimeHelpers)
	src.WriteString("\nfunc Fn(args []core.Value, dispatch func(uint32, []core.Value) core.Value) core.Value {\n")
	src.WriteString("\tvar self func([]core.Value) core.Value\n")
	src.WriteString("\t_ = self\n")
	src.WriteString("\tself = func(a []core.Value) core.Value {\n")
	src.WriteString("\t\t_ = a\n")
	// param frame slots
	for i, p := range cl.Params {
		src.WriteString(fmt.Sprintf("\t\tvar %s core.Value = a[%d]\n", vVar(p), i))
		src.WriteString(fmt.Sprintf("\t\t_ = %s\n", vVar(p)))
	}
	// let frame slots (zero-valued; assigned by setV at their LET site)
	for id := range letNames {
		if _, isParam := scope.frameParam(cl.Params, id); !isParam {
			src.WriteString(fmt.Sprintf("\t\tvar %s core.Value\n", vVar(id)))
			src.WriteString(fmt.Sprintf("\t\t_ = %s\n", vVar(id)))
		}
	}
	src.WriteString("\t\treturn " + bodySrc + "\n")
	src.WriteString("\t}\n")
	src.WriteString("\treturn self(args)\n")
	src.WriteString("}\n")

	// Build under a temp dir whose go.mod points back at the kernel module
	// so `form-kernel-go/core` resolves to the very source this kernel was
	// built from (matching build IDs → plugin.Open accepts the shared core).
	dir, err := os.MkdirTemp("", "form-jitv-")
	if err != nil {
		return nil, fmt.Errorf("mkdtemp: %w", err)
	}
	srcPath := filepath.Join(dir, "main.go")
	if err := os.WriteFile(srcPath, []byte(src.String()), 0o644); err != nil {
		return nil, fmt.Errorf("write source: %w", err)
	}
	goVer := readHostGoVersion()
	modContents := fmt.Sprintf("module form_jitv\n\ngo %s\n\nrequire form-kernel-go v0.0.0\n\nreplace form-kernel-go => %s\n", goVer, srcRoot)
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(modContents), 0o644); err != nil {
		return nil, fmt.Errorf("write go.mod: %w", err)
	}
	soPath := filepath.Join(dir, "plugin.so")
	cmd := exec.Command("go", "build", "-buildmode=plugin", "-o", soPath, srcPath)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=")
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Errorf("go build (value-jit) failed: %v\n%s", err, string(out))
	}
	p, err := plugin.Open(soPath)
	if err != nil {
		return nil, fmt.Errorf("plugin.Open: %w", err)
	}
	sym, err := p.Lookup("Fn")
	if err != nil {
		return nil, fmt.Errorf("plugin.Lookup: %w", err)
	}
	fn, ok := sym.(jitValueFn)
	if !ok {
		return nil, fmt.Errorf("plugin.Lookup: Fn has wrong type %T", sym)
	}
	return fn, nil
}

// frameParam — was this NameID one of the params? (helper for slot dedup)
func (s *vScope) frameParam(params []NameID, id NameID) (int, bool) {
	for i, p := range params {
		if p == id {
			return i, true
		}
	}
	return 0, false
}

// vRuntimeHelpers — emitted verbatim into every Value-typed plugin. Mirrors
// the walker's truthy / math / compare / logic semantics so the JIT'd answer
// is identical to walked.
const vRuntimeHelpers = `func truthyV(v core.Value) bool {
	switch v.Kind {
	case core.VBool:
		return v.Bool
	case core.VInt:
		return v.Int != 0
	case core.VNull:
		return false
	}
	return true
}

func setV(p *core.Value, val core.Value) core.Value { *p = val; return val }

func mathV(op int, a, b core.Value) core.Value {
	if a.Kind == core.VFloat || b.Kind == core.VFloat {
		l := a.AsFloat()
		r := b.AsFloat()
		switch op {
		case 0:
			return core.Value{Kind: core.VFloat, Float: l + r}
		case 1:
			return core.Value{Kind: core.VFloat, Float: l - r}
		case 2:
			return core.Value{Kind: core.VFloat, Float: l * r}
		case 3:
			return core.Value{Kind: core.VFloat, Float: l / r}
		case 4:
			return core.Value{Kind: core.VFloat, Float: l - math.Floor(l/r)*r}
		}
	}
	x := a.Int
	y := b.Int
	switch op {
	case 0:
		return core.Value{Kind: core.VInt, Int: x + y}
	case 1:
		return core.Value{Kind: core.VInt, Int: x - y}
	case 2:
		return core.Value{Kind: core.VInt, Int: x * y}
	case 3:
		return core.Value{Kind: core.VInt, Int: x / y}
	case 4:
		return core.Value{Kind: core.VInt, Int: x % y}
	}
	return core.Value{Kind: core.VNull}
}

func cmpV(op int, a, b core.Value) core.Value {
	// Comparisons acknowledge with the 0/1 integer states (axiom-1) —
	// mirrors the walker's RBasicCompare arm exactly.
	if a.Kind == core.VFloat || b.Kind == core.VFloat {
		l := a.AsFloat()
		r := b.AsFloat()
		var res bool
		switch op {
		case 0:
			res = l == r
		case 1:
			res = l != r
		case 2:
			res = l < r
		case 3:
			res = l <= r
		case 4:
			res = l > r
		case 5:
			res = l >= r
		}
		if res {
			return core.Value{Kind: core.VInt, Int: 1}
		}
		return core.Value{Kind: core.VInt, Int: 0}
	}
	x := a.Int
	y := b.Int
	var res bool
	switch op {
	case 0:
		res = x == y
	case 1:
		res = x != y
	case 2:
		res = x < y
	case 3:
		res = x <= y
	case 4:
		res = x > y
	case 5:
		res = x >= y
	}
	if res {
		return core.Value{Kind: core.VInt, Int: 1}
	}
	return core.Value{Kind: core.VInt, Int: 0}
}
`

// emitVExpr — recipe NodeID → a core.Value-typed Go expression. Unsupported
// shapes raise jitCompileError; the caller maps that to a walker fallback.
func emitVExpr(k *Kernel, node NodeID, scope *vScope) (string, error) {
	if node.Level == LevelTrivial {
		return emitVTrivial(k, node)
	}
	cat := k.category(node)
	kids := k.children(node)

	switch cat.Type {
	case RBasicIdent:
		id := k.identID(node)
		if g, ok := scope.frame[id]; ok {
			return g, nil
		}
		return "", unsupported(fmt.Sprintf("jitv: unbound identifier %q", k.nameStr(id)))

	case RBasicMath:
		return emitVMath(k, cat.Inst, kids, scope)

	case RBasicCompare:
		return emitVCompare(k, cat.Inst, kids, scope)

	case RBasicLogic:
		return emitVLogic(k, cat.Inst, kids, scope)

	case RBasicCond:
		return emitVCond(k, cat.Inst, kids, scope)

	case RBasicBlock:
		return emitVBlock(k, cat.Inst, kids, scope)

	case RBasicList:
		var elems []string
		for _, kid := range kids {
			s, err := emitVExpr(k, kid, scope)
			if err != nil {
				return "", err
			}
			elems = append(elems, s)
		}
		return "core.Value{Kind: core.VList, List: []core.Value{" + strings.Join(elems, ", ") + "}}", nil

	case RBasicFnCall:
		return emitVFnCall(k, kids, scope)

	case RBasicFnDef:
		return "", unsupported("jitv: nested defn not supported")
	}
	return "", unsupported(fmt.Sprintf("jitv: unsupported arm type %d", cat.Type))
}

func emitVTrivial(k *Kernel, node NodeID) (string, error) {
	switch node.Type {
	case TrivInt:
		v := int64(int32(node.Inst))
		return fmt.Sprintf("core.Value{Kind: core.VInt, Int: %d}", v), nil
	case TrivBool:
		if node.Inst != 0 {
			return "core.Value{Kind: core.VBool, Bool: true}", nil
		}
		return "core.Value{Kind: core.VBool, Bool: false}", nil
	case TrivString:
		s := k.nameStr(NameID(node.Inst))
		return fmt.Sprintf("core.Value{Kind: core.VStr, Str: %s}", strconv.Quote(s)), nil
	}
	return "", unsupported(fmt.Sprintf("jitv: trivial type %d not supported", node.Type))
}

// mathOpCode / cmpOpCode — map kernel op instances to the helper's int codes.
func mathOpCode(op uint32) (int, bool) {
	switch op {
	case RMathPlus:
		return 0, true
	case RMathMinus:
		return 1, true
	case RMathMultiply:
		return 2, true
	case RMathDivide:
		return 3, true
	case RMathModulo:
		return 4, true
	}
	return 0, false
}

func cmpOpCode(op uint32) (int, bool) {
	switch op {
	case RCompareEq:
		return 0, true
	case RCompareNe:
		return 1, true
	case RCompareLt:
		return 2, true
	case RCompareLe:
		return 3, true
	case RCompareGt:
		return 4, true
	case RCompareGe:
		return 5, true
	}
	return 0, false
}

func emitVMath(k *Kernel, op uint32, kids []NodeID, scope *vScope) (string, error) {
	if len(kids) != 2 {
		return "", unsupported("jitv: math expects 2 args")
	}
	code, ok := mathOpCode(op)
	if !ok {
		return "", unsupported(fmt.Sprintf("jitv: math op %d", op))
	}
	a, err := emitVExpr(k, kids[0], scope)
	if err != nil {
		return "", err
	}
	b, err := emitVExpr(k, kids[1], scope)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("mathV(%d, %s, %s)", code, a, b), nil
}

func emitVCompare(k *Kernel, op uint32, kids []NodeID, scope *vScope) (string, error) {
	if len(kids) != 2 {
		return "", unsupported("jitv: compare expects 2 args")
	}
	code, ok := cmpOpCode(op)
	if !ok {
		return "", unsupported(fmt.Sprintf("jitv: compare op %d", op))
	}
	a, err := emitVExpr(k, kids[0], scope)
	if err != nil {
		return "", err
	}
	b, err := emitVExpr(k, kids[1], scope)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("cmpV(%d, %s, %s)", code, a, b), nil
}

func emitVLogic(k *Kernel, op uint32, kids []NodeID, scope *vScope) (string, error) {
	switch op {
	case RLogicAnd:
		if len(kids) != 2 {
			return "", unsupported("jitv: and expects 2 args")
		}
		a, err := emitVExpr(k, kids[0], scope)
		if err != nil {
			return "", err
		}
		b, err := emitVExpr(k, kids[1], scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("func() core.Value { if !truthyV(%s) { return core.Value{Kind: core.VBool, Bool: false} }; return core.Value{Kind: core.VBool, Bool: truthyV(%s)} }()", a, b), nil
	case RLogicOr:
		if len(kids) != 2 {
			return "", unsupported("jitv: or expects 2 args")
		}
		a, err := emitVExpr(k, kids[0], scope)
		if err != nil {
			return "", err
		}
		b, err := emitVExpr(k, kids[1], scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("func() core.Value { if truthyV(%s) { return core.Value{Kind: core.VBool, Bool: true} }; return core.Value{Kind: core.VBool, Bool: truthyV(%s)} }()", a, b), nil
	case RLogicNot:
		if len(kids) != 1 {
			return "", unsupported("jitv: not expects 1 arg")
		}
		a, err := emitVExpr(k, kids[0], scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("core.Value{Kind: core.VBool, Bool: !truthyV(%s)}", a), nil
	}
	return "", unsupported(fmt.Sprintf("jitv: logic op %d", op))
}

func emitVCond(k *Kernel, op uint32, kids []NodeID, scope *vScope) (string, error) {
	if len(kids) < 2 {
		return "", unsupported("jitv: cond expects at least 2 kids")
	}
	cond, err := emitVExpr(k, kids[0], scope)
	if err != nil {
		return "", err
	}
	then, err := emitVExpr(k, kids[1], scope)
	if err != nil {
		return "", err
	}
	var elsRet string
	if op == RCondIfThenElse && len(kids) >= 3 {
		els, e := emitVExpr(k, kids[2], scope)
		if e != nil {
			return "", e
		}
		elsRet = "return " + els
	} else {
		elsRet = "return core.Value{Kind: core.VNull}"
	}
	return fmt.Sprintf("func() core.Value { if truthyV(%s) { return %s }; %s }()", cond, then, elsRet), nil
}

func emitVBlock(k *Kernel, op uint32, kids []NodeID, scope *vScope) (string, error) {
	switch op {
	case RBlockLet:
		if len(kids) != 2 {
			return "", unsupported("jitv: let expects 2 kids")
		}
		id := k.identID(kids[0])
		g, ok := scope.frame[id]
		if !ok {
			// Should have been collected; declare lazily as a fallback.
			g = vVar(id)
			scope.frame[id] = g
		}
		valSrc, err := emitVExpr(k, kids[1], scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("setV(&%s, %s)", g, valSrc), nil
	case RBlockDo, RBlockSequence:
		if len(kids) == 0 {
			return "core.Value{Kind: core.VNull}", nil
		}
		if len(kids) == 1 {
			return emitVExpr(k, kids[0], scope)
		}
		var b strings.Builder
		b.WriteString("func() core.Value {\n")
		for i, c := range kids {
			expr, err := emitVExpr(k, c, scope)
			if err != nil {
				return "", err
			}
			if i == len(kids)-1 {
				b.WriteString("\t\t\treturn " + expr + "\n")
			} else {
				b.WriteString("\t\t\t_ = " + expr + "\n")
			}
		}
		b.WriteString("\t\t}()")
		return b.String(), nil
	}
	return "", unsupported(fmt.Sprintf("jitv: block op %d", op))
}

func emitVFnCall(k *Kernel, kids []NodeID, scope *vScope) (string, error) {
	if len(kids) < 1 {
		return "", unsupported("jitv: fncall has no callee")
	}
	callee := kids[0]
	var nameID NameID
	if callee.Level == LevelTrivial && callee.Type == TrivString {
		nameID = NameID(callee.Inst)
	} else {
		cat := k.category(callee)
		if cat.Type == RBasicIdent {
			nameID = k.identID(callee)
		} else {
			return "", unsupported("jitv: dynamic callee not supported")
		}
	}
	name := k.nameStr(nameID)

	// Self-recursion stays a native Go call — no dispatch hop.
	if nameID == scope.selfName {
		args, err := emitVArgs(k, kids[1:], scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("self([]core.Value{%s})", args), nil
	}

	// Defensive lowering: arithmetic / compare / logic / cond may appear as
	// s-expression FNCALLs rather than typed arms. Lower them so they never
	// hit dispatch (there is no "add" native to resolve).
	if code, ok := map[string]int{"add": 0, "sub": 1, "mul": 2, "div": 3, "mod": 4}[name]; ok && len(kids) == 3 {
		a, err := emitVExpr(k, kids[1], scope)
		if err != nil {
			return "", err
		}
		b, err := emitVExpr(k, kids[2], scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("mathV(%d, %s, %s)", code, a, b), nil
	}
	if code, ok := map[string]int{"eq": 0, "ne": 1, "lt": 2, "le": 3, "gt": 4, "ge": 5}[name]; ok && len(kids) == 3 {
		a, err := emitVExpr(k, kids[1], scope)
		if err != nil {
			return "", err
		}
		b, err := emitVExpr(k, kids[2], scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("cmpV(%d, %s, %s)", code, a, b), nil
	}
	switch name {
	case "and", "or":
		op := RLogicAnd
		if name == "or" {
			op = RLogicOr
		}
		return emitVLogic(k, op, kids[1:], scope)
	case "not":
		return emitVLogic(k, RLogicNot, kids[1:], scope)
	case "if":
		op := RCondIfThen
		if len(kids[1:]) >= 3 {
			op = RCondIfThenElse
		}
		return emitVCond(k, op, kids[1:], scope)
	}

	// Everything else — a native or another Form function — routes through
	// the kernel-supplied dispatch by interned NameID.
	args, err := emitVArgs(k, kids[1:], scope)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("dispatch(%d, []core.Value{%s})", uint32(nameID), args), nil
}

func emitVArgs(k *Kernel, kids []NodeID, scope *vScope) (string, error) {
	parts := make([]string, 0, len(kids))
	for _, kid := range kids {
		s, err := emitVExpr(k, kid, scope)
		if err != nil {
			return "", err
		}
		parts = append(parts, s)
	}
	return strings.Join(parts, ", "), nil
}

// kernelSourceRoot — locate the kernel module root (the dir holding go.mod +
// core/) so the plugin's replace directive resolves form-kernel-go/core to the
// exact source this binary was built from. FORM_KERNEL_SRC wins; otherwise we
// probe cwd and the executable's directory. Returns an error (→ walker
// fallback) when no source root is present.
func kernelSourceRoot() (string, error) {
	if env := os.Getenv("FORM_KERNEL_SRC"); env != "" {
		if isKernelRoot(env) {
			abs, _ := filepath.Abs(env)
			return abs, nil
		}
		return "", fmt.Errorf("FORM_KERNEL_SRC=%q is not a kernel source root (no core/core.go)", env)
	}
	candidates := []string{}
	if wd, err := os.Getwd(); err == nil {
		candidates = append(candidates, wd, filepath.Join(wd, "form-kernel-go"))
	}
	if exe, err := os.Executable(); err == nil {
		candidates = append(candidates, filepath.Dir(exe))
	}
	for _, c := range candidates {
		if isKernelRoot(c) {
			abs, _ := filepath.Abs(c)
			return abs, nil
		}
	}
	return "", fmt.Errorf("kernel source root not found (set FORM_KERNEL_SRC); value-JIT unavailable, walker still runs")
}

func isKernelRoot(dir string) bool {
	if _, err := os.Stat(filepath.Join(dir, "core", "core.go")); err != nil {
		return false
	}
	if _, err := os.Stat(filepath.Join(dir, "go.mod")); err != nil {
		return false
	}
	return true
}

// applyClosureValue — invoke a closure with pre-evaluated args, preferring its
// Value-typed JIT plugin when compiled, else walking its body in a fresh call
// frame. The dispatch it hands the plugin resolves the callee's OWN callees
// against the callee's definition env (cl.Env), so mutual recursion across
// JIT'd functions threads correctly.
func (k *Kernel) applyClosureValue(cl *Closure, args []Value) Value {
	bodyKey := nodeIDKey(cl.Body)
	if fnv, ok := k.jitCompiledGoV[bodyKey]; ok {
		dispatch := func(nid uint32, as []core.Value) core.Value {
			return k.callValueByName(NameID(nid), cl.Env, as)
		}
		return fnv(args, dispatch)
	}
	call := NewCallFrame(cl.Env, len(cl.Params))
	for i, p := range cl.Params {
		if i < len(args) {
			call.Bind(p, args[i])
		}
	}
	return k.walk(cl.Body, call)
}

// callValueByName — resolve a NameID to its callable (env-aware native, plain
// native, or closure) and invoke it with pre-evaluated args. Mirrors the
// walker's FNCALL resolution order exactly, so a JIT'd call returns the walked
// answer. This is the dispatch a Value-typed plugin calls for every native or
// cross-function call site.
func (k *Kernel) callValueByName(name NameID, env *Frame, args []Value) Value {
	if ne, ok := k.envNatives[name]; ok {
		if _, shadowed := env.Lookup(name); !shadowed {
			return ne.Fn(k, env, args)
		}
	}
	if ne, ok := k.natives[name]; ok {
		if _, shadowed := env.Lookup(name); !shadowed {
			return ne.Fn(k, args)
		}
	}
	v, ok := env.Lookup(name)
	if !ok {
		panic(fmt.Sprintf("jit-dispatch: unbound %q", k.nameStr(name)))
	}
	if v.Kind != VClosure {
		panic(fmt.Sprintf("jit-dispatch: %q is not callable", k.nameStr(name)))
	}
	return k.applyClosureValue(v.Cl, args)
}
